# Generated by Django 5.2.6 on 2025-09-09 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField(help_text='Durée (HH:MM:SS)')),
                ('booking_type', models.CharField(choices=[('privée', 'Privée'), ('publique', 'Publique')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=100)),
                ('category_game', models.CharField(max_length=50)),
                ('nb_player_min_game', models.IntegerField()),
                ('nb_player_max_game', models.IntegerField()),
                ('stock_game', models.IntegerField(default=0)),
                ('availability_game', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_table', models.IntegerField(unique=True)),
                ('capacity_table', models.IntegerField()),
                ('state_table', models.CharField(choices=[('libre', 'Libre'), ('privée', 'Privée'), ('publique', 'Publique')], default='libre', max_length=10)),
                ('code_table', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
