# Generated by Django 5.2.6 on 2025-09-05 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=100)),
                ('category_game', models.CharField(max_length=50)),
                ('nb_player_min_game', models.IntegerField()),
                ('nb_player_max_game', models.IntegerField()),
                ('stock_game', models.IntegerField(default=0)),
                ('availability_game', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fav_game', models.ManyToManyField(blank=True, related_name='fans', to='tables_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_table', models.IntegerField(unique=True)),
                ('capacity_table', models.IntegerField()),
                ('state_table', models.CharField(choices=[('libre', 'Libre'), ('privée', 'Privée'), ('publique', 'Publique')], default='libre', max_length=10)),
                ('code_table', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_table', models.ManyToManyField(blank=True, related_name='tables', to='tables_app.customer')),
                ('game_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Durée en minutes')),
                ('booking_type', models.CharField(choices=[('privée', 'Privée'), ('publique', 'Publique')], max_length=10)),
                ('main_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tables_app.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_app.table')),
            ],
        ),
    ]
