# Generated by Django 5.2.6 on 2025-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
