# Generated by Django 5.2.6 on 2025-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
