# Generated by Django 5.2.6 on 2025-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0003_remove_game_image_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration_game',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
