# Generated by Django 5.2.6 on 2025-09-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_initial'),
        ('tables_app', '0004_game_duration_game_game_presentation'),
    ]

    operations = [
    ]
