# Generated by Django 5.2.6 on 2025-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0005_merge_20250909_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nb_player_max_game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='nb_player_min_game',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
