# Generated by Django 5.2.6 on 2025-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_booking_code'),
        ('tables_app', '0007_alter_booking_main_customer_and_more'),
    ]

    operations = [
    ]
