# Generated by Django 5.2.6 on 2025-09-11 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0008_merge_20250911_0942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='code',
        ),
        migrations.AlterField(
            model_name='table',
            name='customer_table',
            field=models.ManyToManyField(blank=True, related_name='joined_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
