# Generated by Django 5.2.6 on 2025-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0009_remove_booking_code_alter_table_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
