# Generated by Django 5.2.6 on 2025-09-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0010_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables_app.game'),
        ),
    ]
