# Generated by Django 5.2.6 on 2025-09-16 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0011_booking_custom_game_booking_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='max_players',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
