# Generated by Django 5.2.6 on 2025-09-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0012_booking_max_players_booking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity_table',
            field=models.IntegerField(default=12),
        ),
    ]
